#!/usr/bin/env bash
# This script tells a story from /etc/passwd using IFS and a while loop

while IFS=':' read -r username password uid gid userinfo homedir shell; do
  echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $userinfo"
done < /etc/passwd
